# Generated by Django 4.1.1 on 2022-10-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.DateField()),
                ('lugar', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_comuna', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=2)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('mensaje', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'consultas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id_convenio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_convenio', models.CharField(max_length=30)),
                ('descuento', models.IntegerField()),
            ],
            options={
                'db_table': 'convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_especialidad', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('rut_especialista', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especialistas')),
            ],
            options={
                'db_table': 'especialista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaAtencion',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('motivo_consulta', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'ficha_atencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=20)),
                ('telefono', models.IntegerField()),
                ('contrasenia', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('profesion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id_prevision', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_prevision', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'prevision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_region', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_taller', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='talleres')),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTitulo',
            fields=[
                ('id_titulo', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_titulo', models.CharField(max_length=30)),
                ('universidad', models.CharField(max_length=30)),
                ('annio', models.IntegerField()),
            ],
            options={
                'db_table': 'tipo_titulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('rut_tutor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidio_p', models.CharField(max_length=20)),
                ('apellido_m', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('contrasenia', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tutor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosAdmin',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_admin', models.CharField(max_length=40)),
                ('correo_admin', models.CharField(max_length=30)),
                ('contrasenia', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuarios_admin',
                'managed': False,
            },
        ),
    ]
