# Generated by Django 4.1.1 on 2022-11-03 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=2, null=True)),
                ('correo', models.CharField(max_length=30, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('opciones_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'devolución']], null=True)),
                ('mensaje', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id_convenio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_convenio', models.CharField(max_length=30, null=True)),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('rut_especialista', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('dv', models.CharField(max_length=1, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('correo', models.CharField(max_length=40)),
                ('telefono', models.IntegerField(null=True)),
                ('precio_consulta', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especialistas')),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('contrasenia', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.convenio')),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id_prevision', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_prevision', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titulo', models.CharField(max_length=40)),
                ('universidad', models.CharField(max_length=40)),
                ('annio_egreso', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('rut_tutor', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=50, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id_taller', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_taller', models.CharField(max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='talleres')),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialista')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.prevision'),
        ),
        migrations.CreateModel(
            name='FichaAtencion',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('motivo_consulta', models.CharField(blank=True, max_length=500, null=True)),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialista')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='especialista',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.region'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='tipo_titulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.titulo'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=30, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.IntegerField(null=True)),
                ('lugar', models.CharField(blank=True, max_length=30, null=True)),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialista')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente')),
            ],
        ),
    ]
