# Generated by Django 4.1.1 on 2022-10-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titulo', models.CharField(max_length=40)),
                ('universidad', models.CharField(max_length=40)),
                ('annio_egreso', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TipoTitulo',
        ),
        migrations.DeleteModel(
            name='UsuariosAdmin',
        ),
        migrations.AlterModelOptions(
            name='boleta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consultas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='convenio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='especialista',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fichaatencion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prevision',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
    ]
