# Generated by Django 4.1.1 on 2022-10-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_titulo_delete_tipotitulo_delete_usuariosadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comuna',
            name='desc_comuna',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='desc_especialidad',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='apellido_m',
        ),
        migrations.RemoveField(
            model_name='especialista',
            name='apellido_p',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido_m',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido_p',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='profesion',
        ),
        migrations.RemoveField(
            model_name='prevision',
            name='desc_prevision',
        ),
        migrations.RemoveField(
            model_name='region',
            name='desc_region',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='apellidio_p',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='apellido_m',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='contrasenia',
        ),
        migrations.AddField(
            model_name='boleta',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialista'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='nombre_comuna',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.region'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='opciones_consulta',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'devolución']], null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='nombre_especialidad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialidad'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.region'),
        ),
        migrations.AddField(
            model_name='especialista',
            name='tipo_titulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.titulo'),
        ),
        migrations.AddField(
            model_name='fichaatencion',
            name='especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialista'),
        ),
        migrations.AddField(
            model_name='fichaatencion',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.convenio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prevision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.prevision'),
        ),
        migrations.AddField(
            model_name='prevision',
            name='nombre_prevision',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='nombre_region',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.especialista'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.paciente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='correo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='mensaje',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='nombre',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nombre_convenio',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='correo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='rut_especialista',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichaatencion',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut_paciente',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre_taller',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='correo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='rut_tutor',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='boleta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cita',
            table=None,
        ),
        migrations.AlterModelTable(
            name='comuna',
            table=None,
        ),
        migrations.AlterModelTable(
            name='consultas',
            table=None,
        ),
        migrations.AlterModelTable(
            name='convenio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='especialidad',
            table=None,
        ),
        migrations.AlterModelTable(
            name='especialista',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fichaatencion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paciente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='prevision',
            table=None,
        ),
        migrations.AlterModelTable(
            name='region',
            table=None,
        ),
        migrations.AlterModelTable(
            name='taller',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tutor',
            table=None,
        ),
    ]
