# Generated by Django 4.1.1 on 2022-11-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_cita_hora_alter_cita_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
