# Generated by Django 4.1.1 on 2022-12-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_prevision_options_remove_especialista_dv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='precio',
        ),
        migrations.AddField(
            model_name='taller',
            name='lugar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
