# Generated by Django 4.1.1 on 2022-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cita_paciente_cita_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.IntegerField(choices=[[0, '12:00'], [1, '13:00'], [2, '14:00'], [3, '15:00'], [4, '16:00'], [5, '17:00'], [6, '18:00'], [7, '19:00'], [8, '20:00']], null=True),
        ),
    ]
