# Generated by Django 4.1.1 on 2022-10-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cita_hora'),
        ('app', '0003_remove_comuna_desc_comuna_and_more'),
    ]

    operations = [
    ]
