# Generated by Django 4.1.1 on 2022-11-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cita_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.IntegerField(choices=[[0, 'Programada'], [1, 'Atendido'], [2, 'Cancelada']], null=True),
        ),
    ]
