# Generated by Django 4.1.1 on 2022-11-29 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_cita',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Estado cita',
                'verbose_name_plural': 'Estados citas',
                'db_table': 'Estado_Cita',
            },
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.estado_cita'),
        ),
    ]
